/**
 * Exports live Postgres function and trigger definitions from the local
 * Supabase DB into db/sql/*.sql for local inspection.
 *
 * Usage: pnpm db:export
 *
 * These files are generated and gitignored — do not commit them.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import pg from "pg";

const ROOT_DIR = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUTPUT_DIR = join(ROOT_DIR, "db", "sql");
const FUNCTIONS_PATH = join(OUTPUT_DIR, "functions.sql");
const TRIGGERS_PATH = join(OUTPUT_DIR, "triggers.sql");

const DEFAULT_DATABASE_URL =
  "postgresql://postgres:postgres@127.0.0.1:54322/postgres";

const GENERATED_HEADER = `\
-- GENERATED FILE — do not put this in source control.
-- Regenerated by: pnpm db:export
-- Source: live local Supabase Postgres (pg_get_functiondef / pg_get_triggerdef)
`;

const FUNCTIONS_QUERY = `
select
  p.proname as name,
  coalesce(pg_get_function_identity_arguments(p.oid), '') as args,
  pg_get_functiondef(p.oid) as definition
from pg_proc p
join pg_namespace n on n.oid = p.pronamespace
where n.nspname = 'public'
  and p.prokind in ('f', 'p', 'w')
  and not exists (
    select 1
    from pg_depend d
    join pg_extension e on e.oid = d.refobjid
    where d.objid = p.oid
      and d.deptype = 'e'
  )
order by p.proname, pg_get_function_identity_arguments(p.oid);
`;

const TRIGGERS_QUERY = `
select
  n.nspname as schema_name,
  c.relname as table_name,
  t.tgname as name,
  pg_get_triggerdef(t.oid, true) as definition
from pg_trigger t
join pg_class c on c.oid = t.tgrelid
join pg_namespace n on n.oid = c.relnamespace
where not t.tgisinternal
  and n.nspname in ('public', 'auth')
order by n.nspname, c.relname, t.tgname;
`;

/**
 * Builds a SQL dump file body from labeled definition rows.
 * @param {Array<{ label: string, definition: string }>} rows
 * @returns {string}
 */
function buildSqlDump(rows) {
  const parts = [GENERATED_HEADER, `\n-- Count: ${rows.length}\n`];

  for (const row of rows) {
    parts.push(
      `\n-- ---------------------------------------------------------------------------\n` +
        `-- ${row.label}\n` +
        `-- ---------------------------------------------------------------------------\n\n`,
    );
    parts.push(`${row.definition.trim().replace(/;$/, "")};\n`);
  }

  return parts.join("");
}

/**
 * Exports non-extension public functions and public/auth triggers.
 */
async function main() {
  const databaseUrl =
    process.env.DATABASE_URL ??
    process.env.SUPABASE_DB_URL ??
    DEFAULT_DATABASE_URL;

  const client = new pg.Client({ connectionString: databaseUrl });

  try {
    await client.connect();
  } catch (error) {
    console.error(
      "Failed to connect to local Supabase Postgres.\n" +
        "Start the stack with `pnpm supabase:start` (or `pnpm dev`), then retry.\n" +
        `URL: ${databaseUrl}`,
    );
    throw error;
  }

  try {
    const [functionsResult, triggersResult] = await Promise.all([
      client.query(FUNCTIONS_QUERY),
      client.query(TRIGGERS_QUERY),
    ]);

    const functionsSql = buildSqlDump(
      functionsResult.rows.map((row) => ({
        label: `${row.name}(${row.args})`,
        definition: row.definition,
      })),
    );

    const triggersSql = buildSqlDump(
      triggersResult.rows.map((row) => ({
        label: `${row.schema_name}.${row.table_name}.${row.name}`,
        definition: row.definition,
      })),
    );

    mkdirSync(OUTPUT_DIR, { recursive: true });
    writeFileSync(FUNCTIONS_PATH, functionsSql, "utf8");
    writeFileSync(TRIGGERS_PATH, triggersSql, "utf8");

    console.log(
      `Exported ${functionsResult.rows.length} functions → db/sql/functions.sql`,
    );
    console.log(
      `Exported ${triggersResult.rows.length} triggers → db/sql/triggers.sql`,
    );
  } finally {
    await client.end();
  }
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
