-- Čas: fourth direction `project` and tags bound to a single direction.
-- Generated by drizzle-kit, then reordered and given a backfill so it also runs on
-- databases that already have tags (the resulting schema is exactly what Drizzle expects).
ALTER TYPE "public"."time_direction" ADD VALUE 'project';--> statement-breakpoint
DROP INDEX "time_tags_profile_name_key";--> statement-breakpoint
ALTER TABLE "time_tags" ADD COLUMN "direction" time_direction;--> statement-breakpoint
-- Each existing tag takes the direction it was used with most (ties → enum order),
-- unused tags default to practise.
UPDATE "time_tags" t SET "direction" = COALESCE(
	(
		SELECT e."direction" FROM "time_entries" e
		WHERE e."tag_id" = t."id"
		GROUP BY e."direction"
		ORDER BY count(*) DESC, e."direction"
		LIMIT 1
	),
	'practise'
);--> statement-breakpoint
-- A tag also used under other directions gets a same-named copy per direction ...
INSERT INTO "time_tags" ("profile_id", "direction", "name", "created_by_profile_id", "updated_by_profile_id")
SELECT DISTINCT t."profile_id", e."direction", t."name", t."created_by_profile_id", t."updated_by_profile_id"
FROM "time_tags" t
JOIN "time_entries" e ON e."tag_id" = t."id"
WHERE e."direction" <> t."direction";--> statement-breakpoint
-- ... and those entries are re-pointed to the copy of their own direction.
UPDATE "time_entries" e SET "tag_id" = c."id"
FROM "time_tags" t, "time_tags" c
WHERE e."tag_id" = t."id"
	AND e."direction" <> t."direction"
	AND c."profile_id" = t."profile_id"
	AND c."direction" = e."direction"
	AND c."name" = t."name";--> statement-breakpoint
ALTER TABLE "time_tags" ALTER COLUMN "direction" SET NOT NULL;--> statement-breakpoint
CREATE UNIQUE INDEX "time_tags_profile_direction_name_key" ON "time_tags" USING btree ("profile_id" uuid_ops,"direction" enum_ops,lower(btrim("name")));--> statement-breakpoint
ALTER TABLE "time_tags" ADD CONSTRAINT "time_tags_id_direction_key" UNIQUE("id","direction");--> statement-breakpoint
ALTER TABLE "time_entries" ADD CONSTRAINT "time_entries_tag_direction_fkey" FOREIGN KEY ("tag_id","direction") REFERENCES "public"."time_tags"("id","direction") ON DELETE no action ON UPDATE no action;
